### ISSUE TITLE
ImportError: No module named 'requests'

### ISSUE THREAD

**Issue by jlfrancisco** [paydunya/paydunya-python#1]
Un exception du type ImportError est levée à chaque installation du module via pip. Un bug à corriger please.

**Comment by LeMeteore** [comment]
Error reproduced using Python3.6.4, with Python2, everything worked:

```
>> pipenv install paydunya
Installing paydunya…
Looking in indexes: https://pypi.python.org/simple
Collecting paydunya
  Using cached https://files.pythonhosted.org/packages/78/94/cefb89e03dd4f9be298699c7e82751dc5e41c736a17c42da98c64b39ee77/paydunya-1.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6__vxr_o/paydunya/setup.py", line 70, in <module>
        version=__import__('paydunya').__version__,
      File "/tmp/pip-install-6__vxr_o/paydunya/paydunya/__init__.py", line 11, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    
    ----------------------------------------

Error:  An error occurred while installing paydunya!
  Cache entry deserialization failed, entry ignored
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6__vxr_o/paydunya/
```

**Comment by jlfrancisco** [comment]
Yes, since i'm using Python3.4, i got the error everytime i install it via pip.

I submit a pull request by modifying the setup.py file.

I think it will work for both versions.

**Comment by LeMeteore** [comment]
Out of curiosity... Are you based in Dakar Senegal? Do you mind sharing a drink and talk about Python?

**Comment by jlfrancisco** [comment]
@LeMeteore Yes i am and i do.. Reach me out at this number +221777240843 . I will appreciate. Thanks

**Comment by bambadiagne** [comment]
Merci @jlfrancisco j'ai eu de gros problèmes à l'installer quand je déploie sur heroku (hébergeur).J’étais obligé d'installer en premier requests puis paydunya. @LeMeteore si vous étés contributeur,sachez que le problème n'est pas encore résolu!
Merci d'avance
